### ISSUE TITLE
[Feature] support more feature to custom the time picker 

### ISSUE THREAD

**Issue by ARIEnergy** [toure20/RealTimePicker#2]
For instance , adjust the space of time picker and more features.
And support - without ":" between time

support highlighted when selected time

So do you plan to support more custom features about the framework?  @toure20

**Comment by toure20** [comment]
@ARIEnergy Yes, of course. I will make changes as needed.

**Comment by toure20** [comment]
I will take into account your wishes and try to update new version soon, if there are any ideas please share with me!

**Comment by ARIEnergy** [comment]
So  are you doing these features ?? @toure20

**Comment by toure20** [comment]
> So are you doing these features ?? @toure20

**Comment by toure20** [comment]
> So are you doing these features ?? @toure20

**Comment by toure20** [comment]
> So are you doing these features ?? @toure20

[https://github.com/toure20/RealTimePicker/releases/tag/0.0.6](url)
