### ISSUE TITLE
Detect whether user selected time or not

### ISSUE THREAD

**Issue by thanhH80** [toure20/RealTimePicker#6]
Hi!! How can I know when user selected time or not? 
Can someone tell me? Thank you!!

**Comment by toure20** [comment]
Hi, you can create own optional variable for selected date and assign it using `onDateTimePicked` closure, so if created variable is nil it means user didn't pick the time.
```
var selectedTime: Date?
timePickerView.onDateTimePicked = { [unowned self] time in
   self.selectedTime = time
}

```
> Hi!! How can I know when user selected time or not?
> Can someone tell me? Thank you!!

**Comment by thanhH80** [comment]
Thank you so much, Toure!!
